#############################################################################
# Makefile for building: liboptkeypad.so
# Generated by qmake (2.01a) (Qt 4.7.2) on: Wed Apr 15 15:54:19 2015
# Project:  keyplugin.pro
# Template: lib
# Command: /usr/local/Trolltech/QtEm-4.7.2-arm2.0/bin/qmake -spec /usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/qws/linux-dm365-g++ -o Makefile keyplugin.pro
#############################################################################

####### Compiler, tools and options

CC            = arm_v5t_le-gcc
CXX           = arm_v5t_le-g++
DEFINES       = -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/qws/linux-dm365-g++ -I. -I/usr/local/Trolltech/QtEm-4.7.2-arm2.0/include/QtCore -I/usr/local/Trolltech/QtEm-4.7.2-arm2.0/include/QtNetwork -I/usr/local/Trolltech/QtEm-4.7.2-arm2.0/include/QtGui -I/usr/local/Trolltech/QtEm-4.7.2-arm2.0/include -I.
LINK          = arm_v5t_le-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/QtEm-4.7.2-arm2.0/lib -shared
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/QtEm-4.7.2-arm2.0/lib -lQtGui -L/usr/local/Trolltech/QtEm-4.7.2-arm2.0/lib -lQtNetwork -lQtCore -lpthread 
AR            = arm_v5t_le-ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/QtEm-4.7.2-arm2.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm_v5t_le-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = MyKeyHandler.cpp \
		keypadDriverPlugin.cpp moc_MyKeyHandler.cpp \
		moc_keypadDriverPlugin.cpp
OBJECTS       = MyKeyHandler.o \
		keypadDriverPlugin.o \
		moc_MyKeyHandler.o \
		moc_keypadDriverPlugin.o
DIST          = /usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/include_source_dir.prf \
		keyplugin.pro
QMAKE_TARGET  = optkeypad
DESTDIR       = 
TARGET        = liboptkeypad.so
TARGETD       = liboptkeypad.so

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  $(TARGET)

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)



Makefile: keyplugin.pro  /usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/qws/linux-dm365-g++/qmake.conf /usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/lib/libQtGui.prl \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/lib/libQtNetwork.prl \
		/usr/local/Trolltech/QtEm-4.7.2-arm2.0/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/qws/linux-dm365-g++ -o Makefile keyplugin.pro
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/common/g++.conf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/common/linux.conf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/common/qws.conf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/release.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/lib/libQtGui.prl:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/lib/libQtNetwork.prl:
/usr/local/Trolltech/QtEm-4.7.2-arm2.0/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/QtEm-4.7.2-arm2.0/mkspecs/qws/linux-dm365-g++ -o Makefile keyplugin.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/optkeypad1.0.0 || $(MKDIR) .tmp/optkeypad1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/optkeypad1.0.0/ && $(COPY_FILE) --parents MyKeyHandler.h keypadDriverPlugin.h .tmp/optkeypad1.0.0/ && $(COPY_FILE) --parents MyKeyHandler.cpp keypadDriverPlugin.cpp .tmp/optkeypad1.0.0/ && (cd `dirname .tmp/optkeypad1.0.0` && $(TAR) optkeypad1.0.0.tar optkeypad1.0.0 && $(COMPRESS) optkeypad1.0.0.tar) && $(MOVE) `dirname .tmp/optkeypad1.0.0`/optkeypad1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/optkeypad1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MyKeyHandler.cpp moc_keypadDriverPlugin.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MyKeyHandler.cpp moc_keypadDriverPlugin.cpp
moc_MyKeyHandler.cpp: MyKeyHandler.h
	/usr/local/Trolltech/QtEm-4.7.2-arm2.0/bin/moc $(DEFINES) $(INCPATH) MyKeyHandler.h -o moc_MyKeyHandler.cpp

moc_keypadDriverPlugin.cpp: keypadDriverPlugin.h
	/usr/local/Trolltech/QtEm-4.7.2-arm2.0/bin/moc $(DEFINES) $(INCPATH) keypadDriverPlugin.h -o moc_keypadDriverPlugin.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

MyKeyHandler.o: MyKeyHandler.cpp MyKeyHandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyKeyHandler.o MyKeyHandler.cpp

keypadDriverPlugin.o: keypadDriverPlugin.cpp keypadDriverPlugin.h \
		MyKeyHandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keypadDriverPlugin.o keypadDriverPlugin.cpp

moc_MyKeyHandler.o: moc_MyKeyHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MyKeyHandler.o moc_MyKeyHandler.cpp

moc_keypadDriverPlugin.o: moc_keypadDriverPlugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keypadDriverPlugin.o moc_keypadDriverPlugin.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

